export const BRAZILIAN_STATES = [
  "AC",
  "AL",
  "AP",
  "AM",
  "BA",
  "CE",
  "DF",
  "ES",
  "GO",
  "MA",
  "MT",
  "MS",
  "MG",
  "PA",
  "PB",
  "PR",
  "PE",
  "PI",
  "RJ",
  "RN",
  "RS",
  "RO",
  "RR",
  "SC",
  "SP",
  "SE",
  "TO"
];

export const MONTHS = [
  { name: "Janeiro", value: 0 },
  { name: "Fevereiro", value: 1 },
  { name: "Março", value: 2 },
  { name: "Abril", value: 3 },
  { name: "Maio", value: 4 },
  { name: "Junho", value: 5 },
  { name: "Julho", value: 6 },
  { name: "Agosto", value: 7 },
  { name: "Setembro", value: 8 },
  { name: "Outubro", value: 9 },
  { name: "Novembro", value: 10 },
  { name: "Dezembro", value: 11 }
];